title: "New tool or feature request"
labels: ["Feature Requests"]
body:
  - type: input
    attributes:
      label: "One sentence introduction the new tool or function"
  - type: textarea
    id: tools
    attributes:
      label: Description of new tools or features
      value: |
        ## Description of new tools or features
        ## Scenarios for use
        ## Link or screenshot
  - type: dropdown
    attributes:
      label: Systems
      options:
        - Windows
        - macOS silicon
        - macOS intel
        - Linux(Ubuntu)
