title: "[Feature Requests]"
labels: ["Feature Requests"]
body:
  - type: input
    label: "One sentence introduction the new tool or function"
  - type: markdown
    key: markdown
  - type: dropdown
    attributes:
      label: Systems
      options:
        - Windows
        - macOS silicon
        - macOS intel
        - Linux(Ubuntu)
