title: "[Feature Requests]"
labels: ["Feature Requests"]
body:
  - type: input
    description: "One sentence introduction the new tool or function"
  - type: markdown
    description: "Detailed descriptions of new tools or features, it would be nice to refer to links or screenshots"
  - type: dropdown
    attributes:
      label: Systems
      options:
        - Windows
        - macOS silicon
        - macOS intel
        - Linux(Ubuntu)
