title: "[Feature Requests]"
labels: ["Feature Requests"]
body:
  - type: input
    attributes:
      label: "One sentence introduction the new tool or function"
  - type: markdown
    attributes:
      value: |
        ## Tools or features describtion
        ## Scenarios for use
        ## Link or screenshot
  - type: dropdown
    attributes:
      label: Systems
      options:
        - Windows
        - macOS silicon
        - macOS intel
        - Linux(Ubuntu)
