name: Issue and Discussions Trigger

on:
  issues:
    types: [opened]
  discussion:
    types: [created]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          text="有新的 Discussion"
          if [ ${{ github.event_name }} == "issues" ]; then
            text="有新的 Issue"
          fi
          curl -X POST -H "Content-Type: application/json" \
          -d '{"msg_type":"text","content":{"text":"'$text'"}}' \
          https://open.feishu.cn/open-apis/bot/v2/hook/${{ secrets.FEISHU_BOT_WEBHOOK_URL }}